project:
  type: website
  output-dir: docs
  resources: 
    - "*.png"
    - "*.jpg"

website:
  title: "Davids Coding"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: "https://www.linkedin.com/in/daviddesa03/"
      - icon: youtube
        href: https://youtube.com/@davidscoding
      - icon: github
        href: https://github.com/DavidD003
format:
  html:
    theme: lux
    css: styles.css



